Upload artifact from charm dir. Fail if the charm wasn't found.

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -20,10 +20,12 @@ jobs:
           files=($names)
           for file in "${files[@]}"; do
             if [[ $file == *amd64* ]]; then
-              echo "name=$file" >> $GITHUB_OUTPUT
+              echo "name=charm/$file" >> $GITHUB_OUTPUT
               exit 0
             fi
           done
+          # If an amd64 build wasn't found then fail the run.
+          exit 1
       - uses: actions/upload-artifact@v6
         if: ${{ steps.charm.outputs.name != '' }}
         with:
